objects/updateAccStatusTrig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This can be used to activate and Deactivate trigger directly on Production</description>
    <label>Deactivate trigger</label>
    <fields>
        <fullName>CountofTest__c</fullName>
        <label>CountofTest</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/CL_1115_countTest.cls
global class CL_1115_countTest{
    global void updateCount(){
        updateAccStatusTrig__c trig = updateAccStatusTrig__c.getinstance('0055j000000lPPY');
        system.debug('Value of Trig::::Vijay' + trig);
        if (trig.CountofTest__c == NULL){
            trig.CountofTest__c =1;
            system.debug('Value of Trig::::Vijay' + trig.CountofTest__c);
        }
        else{
            trig.CountofTest__c = trig.CountofTest__c +1;
            system.debug('Value of Trig::::Vijay' + trig.CountofTest__c);
        }
        update trig;
    }
}